services:
    cli.controller.suite_divider:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\SuiteDividerController
        arguments:
            - '@oro_behat_extension.suite.suite_configuration_registry'
        tags:
            - { name: cli.controller, priority: 1300 }

    cli.controller.suite_set_divider:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\SuiteSetDividerController
        arguments:
            - '@oro_behat_extension.suite.suite_configuration_registry'
        tags:
            - { name: cli.controller, priority: 1200 }

    cli.controller.suite:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\SuiteController
        arguments:
            - '@oro_behat_extension.suite.suite_configuration_registry'
            - '@suite.registry'
        tags:
            - { name: cli.controller, priority: 1100 }

    cli.controller.available_features:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\AvailableFeaturesController
        arguments:
            - '@suite.registry'
            - '@specifications.finder'
        tags:
            - { name: cli.controller, priority: 900 }

    cli.controller.available_suite_groups:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\AvailableSuiteGroupsController
        arguments:
            - '@suite.registry'
            - '@specifications.finder'
            - '%oro_test.suite_groups%'
        tags:
            - { name: cli.controller, priority: 800 }

    cli.controller.available_suites:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\AvailableSuitesController
        arguments:
            - '@suite.registry'
            - '@specifications.finder'
        tags:
            - { name: cli.controller, priority: 700 }

    cli.controller.available_suite_sets:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\AvailableSuiteSetsController
        arguments:
            - '@oro_behat_extension.suite.suite_configuration_registry'
        tags:
            - { name: cli.controller, priority: 600 }

    cli.controller.mesure_execution_time:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\MeasureExecutionTimeController
        arguments:
            - '@oro_test.listener.step_duration_measure_subscriber'
            - '@event_dispatcher'
        tags:
            - { name: 'cli.controller' }

    cli.controller.interactive_execution:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\InteractiveExecutionController
        arguments:
            - '@oro_test.listener.interactive_execution_subscriber'
            - '@event_dispatcher'
        tags:
            - { name: 'cli.controller', priority: 500 }

    cli.controller.input_output_controller:
        class: Oro\Bundle\TestFrameworkBundle\Behat\Cli\InputOutputController
        arguments:
            - '@oro_behat_extension.isolation.test_isolation_subscriber'
        tags:
            - { name: 'cli.controller', priority: 100 }
