services:
    _defaults:
        public: true

    oro_test.kernel_service_factory:
        class: Oro\Bundle\TestFrameworkBundle\Behat\ServiceContainer\KernelServiceFactory
        arguments: ['@fob_symfony.kernel']

    oro_entity.entity_alias_resolver:
        class: Oro\Bundle\EntityBundle\ORM\EntityAliasResolver
        factory: ['@oro_test.kernel_service_factory', get]
        arguments: ['oro_entity.entity_alias_resolver']

    oro_security.owner.metadata_provider.chain:
        class: Oro\Bundle\SecurityBundle\Owner\Metadata\OwnershipMetadataProvider
        factory: ['@oro_test.kernel_service_factory', get]
        arguments: ['oro_security.owner.metadata_provider.chain']

    oro_config.global:
        class: Oro\Bundle\ConfigBundle\Config\GlobalScopeManager
        factory: ['@oro_test.kernel_service_factory', get]
        arguments: ['oro_config.global']

    property_accessor:
        class: Symfony\Component\PropertyAccess\PropertyAccessor

    doctrine.orm.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: ['@oro_test.kernel_service_factory', get]
        arguments: ['doctrine.orm.entity_manager']

    file_locator:
        class: Symfony\Component\HttpKernel\Config\FileLocator
        arguments:
            - '@fob_symfony.kernel'
