services:
    oro_test.kernel_service_factory:
        class: Oro\Bundle\TestFrameworkBundle\Behat\ServiceContainer\KernelServiceFactory
        arguments: ['@symfony2_extension.kernel']

    oro_entity.entity_alias_resolver:
        class: Oro\Bundle\EntityBundle\ORM\EntityAliasResolver
        factory: ['@oro_test.kernel_service_factory', get]
        arguments: ['oro_entity.entity_alias_resolver']

    oro_security.owner.metadata_provider.chain:
        class: Oro\Bundle\SecurityBundle\Owner\Metadata\OwnershipMetadataProvider
        # This service marked as public for compatibility with Symfony 4. All dependencies must be refactored after BAP-17037
        public: true
        factory: ['@oro_test.kernel_service_factory', get]
        arguments: ['oro_security.owner.metadata_provider.chain']

    oro_config.global:
        class: Oro\Bundle\ConfigBundle\Config\GlobalScopeManager
        # This service marked as public for compatibility with Symfony 4. All dependencies must be refactored after BAP-17037
        public: true
        factory: ['@oro_test.kernel_service_factory', get]
        arguments: ['oro_config.global']
