services:
    _defaults:
        public: false

    Oro\Bundle\PhpUnitBundle\Command\ContainerTagsDocumentationCommand:
        arguments:
            - '@oro_test.provider.container_tags_documentation_information'
        tags:
            - { name: console.command }
