Oro\Bundle\TestFrameworkBundle\Entity\Item:
    label:           Test Search Bundle Item
    alias:           oro_test_item
    search_template: OroSearchBundle:Test:searchResult.html.twig
    route:
        name: oro_search_results
    fields:
        -
            name: stringValue
            target_type: text
            target_fields: [stringvalue, all_data]
        -
            name: integerValue
            target_type: integer
            target_fields: [integervalue, all_data]
        -
            name: decimalValue
            target_type: decimal
            target_fields: [decimalvalue, all_data]
        -
            name: floatValue
            target_type: decimal
            target_fields: [floatvalue, all_data]
        -
            name: datetimeValue
            target_type: datetime
            target_fields: [datetimevalue, all_data]
        -
            name: blobValue
            target_type: text
            target_fields: [blobvalue, all_data]
        -
            name: phone
            target_type: text
            target_fields: [phone]
