parameters:
    optional_search_listeners:
        - 'oro_search.index_listener'

services:
    _defaults:
        public: true

    fidry_alice_data_fixtures.persistence.persister.doctrine.object_manager_persister:
        class: Oro\Bundle\PhpUnitBundle\Test\DataFixtures\Persister\ObjectManagerPersister
        lazy: true
        arguments:
            - '@doctrine.orm.entity_manager'

    nelmio_alice.fixture_builder.expression_language.lexer.sub_patterns_lexer:
        class: Oro\Bundle\PhpUnitBundle\Test\DataFixtures\Lexer\SubPatternsLexer
        arguments:
            - '@nelmio_alice.fixture_builder.expression_language.lexer.reference_lexer'

    oro_test.fixtures.reflection_property_accessor:
        class: Nelmio\Alice\PropertyAccess\ReflectionPropertyAccessor
        public: false
        decorates: nelmio_alice.property_accessor
        decoration_priority: -10
        arguments:
            - '@oro_test.fixtures.reflection_property_accessor.inner'

    oro_test.alice_file_parser.yaml:
        class: Oro\Bundle\PhpUnitBundle\Test\DataFixtures\AliceYamlParser
        decorates: nelmio_alice.file_parser.chainable.yaml
        arguments:
            - '@oro_test.alice_file_parser.yaml.inner'

    oro_test.reference_resolver:
        class: Oro\Bundle\PhpUnitBundle\Test\DataFixtures\Resolver\AliceReferenceResolver
        public: false
        arguments:
            - '@doctrine'

    oro_test.value_resolver:
        class: Oro\Bundle\PhpUnitBundle\Test\DataFixtures\Resolver\AliceToStringResolver
        arguments:
            - '@oro_test.reference_resolver'

    oro_test.fixture_loader.alice_combined_loader:
        class: Oro\Bundle\PhpUnitBundle\Test\DataFixtures\Loader\AliceCombinedLoader
        lazy: true
        arguments:
            - '@nelmio_alice.files_loader.simple'
            - '@nelmio_alice.data_loader.simple'

    oro_test.fixture_loader.doctrine.persister_loader:
        class: Fidry\AliceDataFixtures\Loader\PersisterLoader
        lazy: true
        arguments:
            - '@oro_test.fixture_loader.alice_combined_loader'
            - '@fidry_alice_data_fixtures.persistence.persister.doctrine'

    oro_test.fixture_loader.doctrine.purger_loader:
        class: Fidry\AliceDataFixtures\Loader\PurgerLoader
        lazy: true
        arguments:
            - '@oro_test.fixture_loader.doctrine.persister_loader'
            - '@fidry_alice_data_fixtures.persistence.purger_factory.doctrine'
            - 'no_purge'

    oro_test.alice_fixture_loader:
        class: Oro\Bundle\PhpUnitBundle\Test\DataFixtures\AliceFixtureLoader
        arguments:
            - '@oro_test.fixture_loader.doctrine.purger_loader'
            - '@file_locator'

    oro_test.reference_repository:
        class: Doctrine\Common\Collections\ArrayCollection
        factory: ['@oro_test.alice_fixture_loader', getReferenceRepository]

    oro_test.provider.container_tags_documentation_information:
        class: Oro\Bundle\PhpUnitBundle\Provider\ContainerTagsDocumentationInformationProvider
        arguments:
            - '%kernel.project_dir%/'

    twig.form.renderer.alias:
        alias: twig.form.renderer
