api:
    entities:
        Oro\Bundle\OrganizationBundle\Entity\BusinessUnit:
            filters:
                fields:
                    name:
                        exclude: false
                    email:
                        exclude: false
            sorters:
                fields:
                    email:
                        exclude: false
        Oro\Bundle\TestFrameworkBundle\Entity\TestDepartment:
            fields:
                title:
                    exclude: false
                    property_path: name
            filters:
                fields:
                    name:
                        exclude: false
        Oro\Bundle\TestFrameworkBundle\Entity\TestEmployee:
            filters:
                fields:
                    name:
                        exclude: false
            sorters:
                fields:
                    position:
                        exclude: false
        Oro\Bundle\TestFrameworkBundle\Entity\TestProduct:
            fields:
                renamedId:
                    property_path: id
                renamedName:
                    property_path: name
            filters:
                fields:
                    renamedName:
                        exclude: false
            sorters:
                fields:
                    renamedName:
                        exclude: false
        Oro\Bundle\TestFrameworkBundle\Entity\TestProductType:
            fields:
                renamedName:
                    property_path: name
            filters:
                fields:
                    renamedName:
                        exclude: false
            sorters:
                fields:
                    renamedName:
                        exclude: false
        Oro\Bundle\TestFrameworkBundle\Entity\TestDefaultAndNull: ~
        Oro\Bundle\TestFrameworkBundle\Entity\TestEntityForNestedObjects:
            fields:
                name:
                    data_type: nestedObject
                    form_options:
                        data_class: Oro\Bundle\TestFrameworkBundle\Entity\TestNestedName
                        by_reference: false
                    fields:
                        firstName: ~
                        lastName: ~
                firstName:
                    exclude: true
                lastName:
                    exclude: true
                relatedEntity:
                    data_type: nestedAssociation
                    fields:
                        __class__:
                            property_path: relatedClass
                        id:
                            property_path: relatedId
                relatedClass:
                    exclude: true
                relatedId:
                    exclude: true
