# this bundle should be excluded from automatic loading
# use \AppKernel to load bundle in test environment only
bundles:
    - { name: FriendsOfBehat\SymfonyExtension\Bundle\FriendsOfBehatSymfonyExtensionBundle }
