oro_item:
    resource:     "@OroPhpUnitBundle/Controller/ItemController.php"
    type:         annotation
    prefix:       /test/item

oro_item_value:
    resource:     "@OroPhpUnitBundle/Controller/ItemValueController.php"
    type:         annotation
    prefix:       /test/item-value

oro_workflow_aware_entity:
    resource:     "@OroPhpUnitBundle/Controller/WorkflowAwareEntityController.php"
    type:         annotation
    prefix:       /test/wfa
