search:
    Oro\Bundle\PhpUnitBundle\Entity\Item:
        label:           Test Search Bundle Item
        alias:           oro_test_item
        search_template: '@OroSearch/Test/searchResult.html.twig'
        route:
            name: oro_search_results
        fields:
            -
                name: id
                target_type: integer
                target_fields: [id]
            -
                name: stringValue
                target_type: text
                target_fields: [stringValue, all_data]
            -
                name: integerValue
                target_type: integer
                target_fields: [integerValue, all_data]
            -
                name: decimalValue
                target_type: decimal
                target_fields: [decimalValue, all_data]
            -
                name: floatValue
                target_type: decimal
                target_fields: [floatValue, all_data]
            -
                name: datetimeValue
                target_type: datetime
                target_fields: [datetimeValue, all_data]
            -
                name: blobValue
                target_type: text
                target_fields: [blobValue, all_data]
            -
                name: phone
                target_type: text
                target_fields: [phone]

    Oro\Bundle\PhpUnitBundle\Entity\Item2:
        label:           Test Search Bundle Item2
        alias:           oro_test_item2
        search_template: '@OroSearch/Test/searchResult.html.twig'
        route:
            name: oro_search_results2

    Oro\Bundle\PhpUnitBundle\Entity\Product:
        label: Test Search Bundle Product
        alias: oro_product_test
        title_fields: [name]
        search_template: '@OroSearch/Test/searchResult.html.twig'
        route:
            name: oro_search_results
        fields:
            -
                name: name
                target_type: text
